### ISSUE TITLE
This needs corrected.

### ISSUE THREAD

**Issue by 7D7-Development** [morethancodenl/mtc-cityhall#11]
This:
Player.Functions.SetJob(job.job)

Needs to be this:
Player.Functions.SetJob(job.job, 0)

**Comment by Mitchel** [comment]
https://github.com/morethancodenl/mtc-cityhall/blob/main/server/server.lua
If you look at the server.lua and then at line 8, this is already there.

**Comment by 7D7-Development** [comment]
I must have had an old version? This was missing from the one I had.
