### ISSUE TITLE
Is there anyway to make it work with um-idcard?

### ISSUE THREAD

**Issue by planeklm** [morethancodenl/mtc-cityhall#9]
Hi,
I've tried multiple things to make it work with um-idcard, however I've had no success.
Any  help will be appreciated!

**Comment by Mitchel** [comment]
What exactly is the problem you are running into @planeklm that you are not getting working? As I think, if you buy an ID card, you should get the right one for [um-idcard](https://github.com/alp1x/um-idcard) right?

**Comment by planeklm** [comment]
> What exactly is the problem you are running into @planeklm that you are not getting working? As I think, if you buy an ID card, you should get the right one for [um-idcard](https://github.com/alp1x/um-idcard) right?

I believe I fixed it awhile ago, so my bad for not closing the problem, I appreciate the help though!

**Comment by Mitchel** [comment]
> > What exactly is the problem you are running into @planeklm that you are not getting working? As I think, if you buy an ID card, you should get the right one for [um-idcard](https://github.com/alp1x/um-idcard) right?
> 
> I believe I fixed it awhile ago, so my bad for not closing the problem, I appreciate the help though!

If you want to share it, be free: make many more people happy! Feel free to open a PR for it.
